### ISSUE TITLE
TranscodeEngine: Unexpected error while transcoding.

### ISSUE THREAD

**Issue by Noloxs** [natario1/Transcoder#146] opened 2021-07-22 09:03 UTC
Hi. 
I encountered a issue related to the MediaMetadataRetriever on a [particular video](https://user-images.githubusercontent.com/5433562/126613239-48548004-2602-4eea-b149-6825d53e7fc6.mp4)
When I attempt to transcode the video, it throws an exception that seems to originate from the MediaMetadataRetriever while attempting to get the videos location metadata.

_NB.: The video is not a natural recorded video but made by saving a power point as a video._

**Transcoder version:** 0.10.3
**Device type:** Samsung Galaxy S21 Ultra
**Android API level:** Android 11 (30)

**Exact steps to reproduce the issue**
Attempt to transcode the attached video using the configuration show below.

**Expected behavior**
The video is transcoded, possibly with some missing metadata

### Imprementation:
```
 DefaultVideoStrategy videoStrategy = DefaultVideoStrategy.atMost(minor, major)
                    .frameRate(30)
                    .bitRate(getBitrate(recipientSize))
                    .keyFrameInterval(99) //This is in seconds and so we only have first keyframe
                    .build();

            FallbackAudioStrategy strategy = FallbackAudioStrategy.builder()
                    .channels(2)
                    .fallBackBitRate(96000)
                    .fallBackSampleRate(44100)
                    .build();

            //issue with devices that gives an error from the rk player that the video is 4k if the video height is higher than the frame screen height (if we rotate then no problem)
            if (videoHeight > videoWidth && videoHeight > recipientSize.getHeight() && rotation == 0) {
                rotation = 90;
            }

            LogHelper.d(TAG, "Transcoding video");
            DataSource source = new FilePathDataSource(video.getMediaPath());
            DataSource clip = new ClipDataSource(source, video.getFromTimeMs() * 1000, video.getToTimeMs() * 1000);

            Transcoder
                    .into(transcodedTemp.getAbsolutePath())
                    .addDataSource(clip)
                    .setAudioTrackStrategy(video.isMuted() ? new RemoveTrackStrategy() : strategy)
                    .setVideoTrackStrategy(videoStrategy)
                    .setVideoRotation(rotation)
                    .setListenerHandler(callbackHandler)
                    .setListener(new TranscoderListener() {
                        public void onTranscodeProgress(double progress) {
                            //there's a bug in the Transcoder listener so it would sometimes return a progress above 1.0
                            progress = Math.min(1.0, progress);
                            listener.onProgress((float) progress);
                        }

                        public void onTranscodeCompleted(int successCode) {
                            transcodingSuccess = true;
                            LogHelper.v(TAG, "VIDEO TRANSCODE SUCCESS");
                            completeTranscodingLatch.countDown();
                        }

                        public void onTranscodeCanceled() {
                            transcodingSuccess = false;
                            LogHelper.e(TAG, "VIDEO TRANSCODE CANCEL");
                            completeTranscodingLatch.countDown();
                        }

                        public void onTranscodeFailed(@NonNull Throwable exception) {
                            transcodingSuccess = false;
                            LogHelper.e(TAG, "VIDEO TRANSCODE FAILURE");
                            LogHelper.logException(exception);
                            completeTranscodingLatch.countDown();
                        }
                    }).transcode();
```

### Exception:
```
    java.lang.IllegalStateException: No retriever available
        at android.media.MediaMetadataRetriever.nativeExtractMetadata(Native Method)
        at android.media.MediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.java:414)
        at com.otaliastudios.transcoder.source.DefaultDataSource.getLocation(DefaultDataSource.java:253)
        at com.otaliastudios.transcoder.source.DataSourceWrapper.getLocation(DataSourceWrapper.java:38)
        at com.otaliastudios.transcoder.source.DataSourceWrapper.getLocation(DataSourceWrapper.java:38)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$location$1.invoke(DefaultTranscodeEngine.kt:54)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$location$1.invoke(DefaultTranscodeEngine.kt:27)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:133)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.<init>(DefaultTranscodeEngine.kt:54)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:32)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by millsjustin** [comment] 2021-08-20 00:10
I attempted reproducing this on several versions. The results were as follows:

- `main (ba8f098)` Cannot reproduce in demo app
- `v0.10.3` Can reproduce in demo app
- `v0.10.2` Can reproduce in demo app
- `v0.10.1` Can reproduce in demo app
- `v0.10.0` Can reproduce in demo app
- `v0.9.1` Cannot reproduce in demo app

I'm not sure what changed to fix this but it seems to be resolved on `main`. That said, it still might be a good idea to catch exceptions thrown by `mMetadata.extractMetadata(METADATA_KEY_LOCATION)` as suggested by @daviduzan in https://github.com/natario1/Transcoder/issues/147

I would be happy to create that PR if you would like.

**Comment by Noloxs** [comment] 2021-08-20 12:08
Do you have any guesstimates regarding the next official release?

As it isn't a blocking issue, we able to wait for it.

**Comment by iNPUTmice** [comment] 2021-09-15 18:06
I can confirm that this appears to be fixed in `main`. However I’m unable to explain why this is fixed by the one commit that makes the difference between 0.10.3 and and main.

**Comment by natario1** [comment] 2021-09-15 19:02
Done!

**Closed by natario1** 2021-09-15 19:02 UTC
